<?php

namespace Database\Seeders;

use Faker\Factory as Faker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $facker = Faker::create();
        DB::table('modules')->insert([
            [
                'panel' => 'Backend',
                'title' => 'Dashboard',
                'controller' => 'dashboard',
                'action' => 'index',
                'icon' => 'fas fa-tachometer-alt',
                'functionality' => 'crud',
                'type' => 'Menu',
                'parent_menu_id' => null,
                'parent_submenu_id' => null,
                'menu_position' => null,
                'submenu_position' => null,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => $facker->DateTime(),
                'created_at' => $facker->DateTime(),
                'updated_at' => $facker->DateTime(),
            ],
            [
                'panel' => 'Backend',
                'title' => 'User Management',
                'controller' => '',
                'action' => '',
                'icon' => 'fas fa-users-cog',
                'functionality' => 'other',
                'type' => 'Menu',
                'parent_menu_id' => null,
                'parent_submenu_id' => null,
                'menu_position' => null,
                'submenu_position' => null,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => $facker->DateTime(),
                'created_at' => $facker->DateTime(),
                'updated_at' => $facker->DateTime(),
            ],
            [
                'panel' => 'Backend',
                'title' => 'Modules',
                'controller' => 'modules',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 2,
                'parent_submenu_id' => null,
                'menu_position' => null,
                'submenu_position' => null,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => $facker->DateTime(),
                'created_at' => $facker->DateTime(),
                'updated_at' => $facker->DateTime(),
            ],
            [
                'panel' => 'Backend',
                'title' => 'Permissions',
                'controller' => 'permissions',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 2,
                'parent_submenu_id' => null,
                'menu_position' => null,
                'submenu_position' => null,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => $facker->DateTime(),
                'created_at' => $facker->DateTime(),
                'updated_at' => $facker->DateTime(),
            ],
            [
                'panel' => 'Backend',
                'title' => 'Roles',
                'controller' => 'roles',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 2,
                'parent_submenu_id' => null,
                'menu_position' => null,
                'submenu_position' => null,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => $facker->DateTime(),
                'created_at' => $facker->DateTime(),
                'updated_at' => $facker->DateTime(),
            ],
            [
                'panel' => 'Backend',
                'title' => 'Templates',
                'controller' => '',
                'action' => '',
                'icon' => 'fas fa-envelope-open-text',
                'functionality' => 'other',
                'type' => 'Menu',
                'parent_menu_id' => null,
                'parent_submenu_id' => null,
                'menu_position' => null,
                'submenu_position' => null,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => $facker->DateTime(),
                'created_at' => $facker->DateTime(),
                'updated_at' => $facker->DateTime(),
            ],
            [
                'panel' => 'Backend',
                'title' => 'Email Templates',
                'controller' => 'emailtemplates',
                'action' => 'index',
                'icon' => 'fas fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 6,
                'parent_submenu_id' => null,
                'menu_position' => null,
                'submenu_position' => null,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => $facker->DateTime(),
                'created_at' => $facker->DateTime(),
                'updated_at' => $facker->DateTime(),
            ],
            [
                'panel' => 'Backend',
                'title' => 'Settings',
                'controller' => 'settings',
                'action' => 'index',
                'icon' => 'fas fa-cog',
                'functionality' => 'crud',
                'type' => 'Menu',
                'parent_menu_id' => null,
                'parent_submenu_id' => null,
                'menu_position' => null,
                'submenu_position' => null,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => $facker->DateTime(),
                'created_at' => $facker->DateTime(),
                'updated_at' => $facker->DateTime(),
            ],
            [
                'panel' => 'Backend',
                'title' => 'Custom Pages',
                'controller' => 'custompages',
                'action' => 'index',
                'icon' => 'fas fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 6,
                'parent_submenu_id' => null,
                'menu_position' => null,
                'submenu_position' => null,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => $facker->DateTime(),
                'created_at' => $facker->DateTime(),
                'updated_at' => $facker->DateTime(),
            ],
            [
                'panel' => 'Backend',
                'title' => 'Users',
                'controller' => 'users',
                'action' => 'index',
                'icon' => 'fas fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 2,
                'parent_submenu_id' => null,
                'menu_position' => null,
                'submenu_position' => null,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => $facker->DateTime(),
                'created_at' => $facker->DateTime(),
                'updated_at' => $facker->DateTime(),
            ],
            [
                'panel' => 'Backend',
                'title' => 'Salons',
                'controller' => 'salons',
                'action' => 'index',
                'icon' => 'fas fa-spa',
                'functionality' => 'crud',
                'type' => 'Menu',
                'parent_menu_id' => null,
                'parent_submenu_id' => null,
                'menu_position' => null,
                'submenu_position' => null,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => $facker->DateTime(),
                'created_at' => $facker->DateTime(),
                'updated_at' => $facker->DateTime(),
            ],
        ]);
    }
}