<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SalonModulesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('salon_modules')->delete();
        
        \DB::table('salon_modules')->insert(array (
            0 => 
            array (
                'id' => 1,
                'panel' => 'Staff',
                'title' => 'Dashboard',
                'controller' => 'dashboard',
                'action' => 'index',
                'icon' => 'dashboard.png',
                'functionality' => 'singleview',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 07:22:43',
                'created_at' => '2022-02-14 07:22:43',
                'updated_at' => '2022-02-14 07:28:54',
            ),
            1 => 
            array (
                'id' => 2,
                'panel' => 'Staff',
                'title' => 'Calendar',
                'controller' => 'calendar',
                'action' => 'index',
                'icon' => 'caleder.png',
                'functionality' => 'singleview',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 07:24:01',
                'created_at' => '2022-02-14 07:24:01',
                'updated_at' => '2022-02-18 08:34:10',
            ),
            2 => 
            array (
                'id' => 3,
                'panel' => 'Staff',
                'title' => 'Sales',
                'controller' => 'sales',
                'action' => 'index',
                'icon' => 'sales.png',
                'functionality' => 'singleview',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 07:29:42',
                'created_at' => '2022-02-14 07:29:42',
                'updated_at' => '2022-02-14 07:29:42',
            ),
            3 => 
            array (
                'id' => 4,
                'panel' => 'Staff',
                'title' => 'Vouchers',
                'controller' => 'vouchers',
                'action' => 'index',
                'icon' => 'Vouchers.png',
                'functionality' => 'crud',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 07:30:21',
                'created_at' => '2022-02-14 07:30:21',
                'updated_at' => '2022-02-14 07:30:21',
            ),
            4 => 
            array (
                'id' => 5,
                'panel' => 'Staff',
                'title' => 'Subscriptions',
                'controller' => 'subscriptions',
                'action' => 'index',
                'icon' => 'refresh.png',
                'functionality' => 'crud',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 07:31:15',
                'created_at' => '2022-02-14 07:31:15',
                'updated_at' => '2022-02-14 07:31:15',
            ),
            5 => 
            array (
                'id' => 6,
                'panel' => 'Staff',
                'title' => 'Clients',
                'controller' => 'clients',
                'action' => 'index',
                'icon' => 'user.png',
                'functionality' => 'crud',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 07:31:59',
                'created_at' => '2022-02-14 07:31:59',
                'updated_at' => '2022-02-14 07:31:59',
            ),
            6 => 
            array (
                'id' => 7,
                'panel' => 'Staff',
                'title' => 'Staff',
                'controller' => 'staff',
                'action' => 'index',
                'icon' => 'staff.png',
                'functionality' => 'crud',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 07:32:32',
                'created_at' => '2022-02-14 07:32:32',
                'updated_at' => '2022-02-14 07:32:32',
            ),
            7 => 
            array (
                'id' => 8,
                'panel' => 'Staff',
                'title' => 'Services',
                'controller' => 'services',
                'action' => 'index',
                'icon' => 'Services.png',
                'functionality' => 'crud',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 08:35:33',
                'created_at' => '2022-02-14 08:35:33',
                'updated_at' => '2022-02-14 08:35:33',
            ),
            8 => 
            array (
                'id' => 9,
                'panel' => 'Staff',
                'title' => 'Products',
                'controller' => 'products',
                'action' => 'index',
                'icon' => 'product.png',
                'functionality' => 'crud',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 08:36:15',
                'created_at' => '2022-02-14 08:36:15',
                'updated_at' => '2022-02-14 08:36:15',
            ),
            9 => 
            array (
                'id' => 10,
                'panel' => 'Staff',
                'title' => 'Reports',
                'controller' => 'reports',
                'action' => 'index',
                'icon' => 'Reports.png',
                'functionality' => 'crud',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 08:37:03',
                'created_at' => '2022-02-14 08:37:03',
                'updated_at' => '2022-02-14 08:37:03',
            ),
            10 => 
            array (
                'id' => 11,
                'panel' => 'Staff',
                'title' => 'Marketing',
                'controller' => 'marketing',
                'action' => 'index',
                'icon' => 'Marketing.png',
                'functionality' => 'crud',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 08:37:55',
                'created_at' => '2022-02-14 08:37:55',
                'updated_at' => '2022-02-14 08:37:55',
            ),
            11 => 
            array (
                'id' => 12,
                'panel' => 'Staff',
                'title' => 'Account Setup',
                'controller' => 'settings',
                'action' => 'index',
                'icon' => 'setting.png',
                'functionality' => 'singleview',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 08:38:45',
                'created_at' => '2022-02-14 08:38:45',
                'updated_at' => '2022-02-14 08:38:58',
            ),
            12 => 
            array (
                'id' => 13,
                'panel' => 'Staff',
                'title' => 'Price Tiers',
                'controller' => 'pricetiers',
                'action' => 'index',
                'icon' => '',
                'functionality' => 'crud',
                'type' => 'Tab',
                'parent_menu_id' => 7,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 09:36:43',
                'created_at' => '2022-02-14 09:36:43',
                'updated_at' => '2022-02-18 09:49:17',
            ),
            13 => 
            array (
                'id' => 14,
                'panel' => 'Staff',
                'title' => 'Roster',
                'controller' => 'roster',
                'action' => 'index',
                'icon' => '',
                'functionality' => 'crud',
                'type' => 'Tab',
                'parent_menu_id' => 7,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 09:37:15',
                'created_at' => '2022-02-14 09:37:15',
                'updated_at' => '2022-02-18 09:52:22',
            ),
            14 => 
            array (
                'id' => 15,
                'panel' => 'Staff',
                'title' => 'Staff Access',
                'controller' => 'salonaccess',
                'action' => 'index',
                'icon' => '',
                'functionality' => 'crud',
                'type' => 'Tab',
                'parent_menu_id' => 7,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 09:37:59',
                'created_at' => '2022-02-14 09:37:59',
                'updated_at' => '2022-02-18 08:35:07',
            ),
            15 => 
            array (
                'id' => 16,
                'panel' => 'Staff',
                'title' => 'Suppliers',
                'controller' => 'suppliers',
                'action' => 'index',
                'icon' => '',
                'functionality' => 'crud',
                'type' => 'Tab',
                'parent_menu_id' => 9,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 09:45:57',
                'created_at' => '2022-02-14 09:45:57',
                'updated_at' => '2022-02-18 10:33:54',
            ),
            16 => 
            array (
                'id' => 17,
                'panel' => 'Staff',
                'title' => 'Categories',
                'controller' => 'categories',
                'action' => 'index',
                'icon' => '',
                'functionality' => 'crud',
                'type' => 'Tab',
                'parent_menu_id' => 8,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 09:47:50',
                'created_at' => '2022-02-14 09:47:50',
                'updated_at' => '2022-02-14 09:47:50',
            ),
            17 => 
            array (
                'id' => 18,
                'panel' => 'Staff',
                'title' => 'Client Photos',
                'controller' => 'clientphotos',
                'action' => 'index',
                'icon' => '',
                'functionality' => 'crud',
                'type' => 'Tab',
                'parent_menu_id' => 6,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-18 09:09:56',
                'created_at' => '2022-02-18 09:09:56',
                'updated_at' => '2022-02-18 09:11:59',
            ),
            18 => 
            array (
                'id' => 19,
                'panel' => 'Staff',
                'title' => 'Client Notes',
                'controller' => 'clientnotes',
                'action' => 'index',
                'icon' => '',
                'functionality' => 'crud',
                'type' => 'Tab',
                'parent_menu_id' => 6,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-18 12:27:11',
                'created_at' => '2022-02-18 09:12:24',
                'updated_at' => '2022-02-18 12:27:11',
            ),
            19 => 
            array (
                'id' => 20,
                'panel' => 'Staff',
                'title' => 'Client Documents',
                'controller' => 'clientdocuments',
                'action' => 'index',
                'icon' => '',
                'functionality' => 'crud',
                'type' => 'Tab',
                'parent_menu_id' => 6,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-18 09:12:51',
                'created_at' => '2022-02-18 09:12:51',
                'updated_at' => '2022-02-18 09:12:51',
            ),
        ));
        
        
    }
}