<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'role_id' => 1,
                'salon_id' => NULL,
                'price_tier_id' => NULL,
                'panel' => 'Backend',
                'auth_key' => '6b3cfefd946bed14fa3284966869ec560e75114f017453be91f96e61cc640141',
                'first_name' => 'master',
                'last_name' => 'admin',
                'username' => 'masteradmin',
                'email' => 'masteradmin@gmail.com',
                'email_otp' => NULL,
                'email_verified' => 1,
                'email_verified_at' => '1984-07-15 12:46:05',
                'password' => '$2y$10$yhTobCYSdAhD1YFdTTDp/.KIZvQbOSDBw.K9Hgit8HLJjkqpcI7Fi',
                'phone_number' => '+19177414907',
                'phone_number_otp' => NULL,
                'phone_number_verified' => 1,
                'phone_number_verified_at' => '1986-09-15 21:24:38',
                'profile_photo' => '',
                'remember_token' => NULL,
                'is_active' => 1,
                'is_active_at' => '2018-10-13 18:16:54',
                'created_at' => '2014-10-25 22:26:21',
                'updated_at' => '1985-11-06 01:21:58',
                'gender' => NULL,
                'date_of_birth' => NULL,
                'address' => NULL,
                'street' => NULL,
                'suburb' => NULL,
                'state' => NULL,
                'postcode' => NULL,
                'description' => NULL,
                'send_sms_notification' => 0,
                'send_email_notification' => 0,
                'recieve_marketing_email' => 0,
                'calendar_booking' => 0,
                'payment_mode' => NULL,
                'stripe_account_id' => NULL,
                'stripe_customer_account_id' => NULL,
                'mailchimp_subscribe_id' => NULL,
                'canva_subscribe_id' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'role_id' => 2,
                'salon_id' => NULL,
                'price_tier_id' => NULL,
                'panel' => 'Backend',
                'auth_key' => '2b2976d681ae3ba9568a700580d72e302ff0bd5f98873ac8c08ef2c7192f5d3d',
                'first_name' => 'Letitia',
                'last_name' => 'Kuphal',
                'username' => 'damore.lisandro',
                'email' => 'deondre.terry@gmail.com',
                'email_otp' => NULL,
                'email_verified' => 1,
                'email_verified_at' => '1974-04-24 08:52:42',
                'password' => '$2y$10$yVkgQEsXv9bBnH./d/Y6A.PhWMI1iuGfGh0QaBU1yt42lgSxskh0e',
            'phone_number' => '(386) 309-7682',
                'phone_number_otp' => NULL,
                'phone_number_verified' => 1,
                'phone_number_verified_at' => '2016-04-13 21:00:36',
                'profile_photo' => '',
                'remember_token' => NULL,
                'is_active' => 1,
                'is_active_at' => '1987-01-11 03:47:55',
                'created_at' => '1987-10-07 00:52:47',
                'updated_at' => '2005-12-30 23:16:02',
                'gender' => NULL,
                'date_of_birth' => NULL,
                'address' => NULL,
                'street' => NULL,
                'suburb' => NULL,
                'state' => NULL,
                'postcode' => NULL,
                'description' => NULL,
                'send_sms_notification' => 0,
                'send_email_notification' => 0,
                'recieve_marketing_email' => 0,
                'calendar_booking' => 0,
                'payment_mode' => NULL,
                'stripe_account_id' => NULL,
                'stripe_customer_account_id' => NULL,
                'mailchimp_subscribe_id' => NULL,
                'canva_subscribe_id' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'role_id' => 4,
                'salon_id' => 1,
                'price_tier_id' => NULL,
                'panel' => 'Backend',
                'auth_key' => '1eda70eaa15785272440cd7ed21b09ebf6c6e6bf44650765a5605412cc73eec4',
                'first_name' => 'Larissa',
                'last_name' => 'Jakubowski',
                'username' => 'fpagac',
                'email' => 'maulik@mailinator.com',
                'email_otp' => NULL,
                'email_verified' => 1,
                'email_verified_at' => '2014-07-30 22:26:11',
                'password' => '$2y$10$djFmuHOvpttkMUlB6LXxUeB.aYLAbGuV5MJ0gJRiThCTQLTRYK9Da',
                'phone_number' => '720-419-7217',
                'phone_number_otp' => NULL,
                'phone_number_verified' => 1,
                'phone_number_verified_at' => '1977-01-24 01:19:05',
                'profile_photo' => '',
                'remember_token' => NULL,
                'is_active' => 1,
                'is_active_at' => '1981-10-08 00:28:17',
                'created_at' => '1982-06-17 19:35:12',
                'updated_at' => '2022-07-14 06:04:08',
                'gender' => NULL,
                'date_of_birth' => NULL,
                'address' => NULL,
                'street' => NULL,
                'suburb' => NULL,
                'state' => NULL,
                'postcode' => NULL,
                'description' => NULL,
                'send_sms_notification' => 0,
                'send_email_notification' => 0,
                'recieve_marketing_email' => 0,
                'calendar_booking' => 0,
                'payment_mode' => 'Test',
                'stripe_account_id' => 'acct_1KsMmFSBtAREZzxu',
                'stripe_customer_account_id' => NULL,
                'mailchimp_subscribe_id' => '2fa1c1acfa0c9c7462541fa85ee9108e',
                'canva_subscribe_id' => NULL,
            ),
            3 => 
            array (
                'id' => 7,
                'role_id' => 5,
                'salon_id' => 1,
                'price_tier_id' => 2,
                'panel' => 'Frontend',
                'auth_key' => '7aff351be67ecc485edb263c4592920b7b5279b874552906ca3ea0a804fa7330',
                'first_name' => 'Alexandra',
                'last_name' => 'Close',
                'username' => 'AlexandraClose158',
                'email' => 'AlexandraClose@mailinator.com',
                'email_otp' => NULL,
                'email_verified' => 0,
                'email_verified_at' => NULL,
                'password' => '$2y$10$ZnMEjFSSiS5kuZ2bRW6.JOipkhqfdVcCsL.A9.mHWGalIUZ93ercS',
                'phone_number' => '089-010-6022',
                'phone_number_otp' => NULL,
                'phone_number_verified' => 0,
                'phone_number_verified_at' => NULL,
                'profile_photo' => '1648630473_user6-128x128.jpg',
                'remember_token' => NULL,
                'is_active' => 1,
                'is_active_at' => '2022-03-30 06:28:10',
                'created_at' => '2022-03-30 06:28:14',
                'updated_at' => '2022-04-19 06:23:02',
                'gender' => NULL,
                'date_of_birth' => NULL,
                'address' => NULL,
                'street' => NULL,
                'suburb' => NULL,
                'state' => NULL,
                'postcode' => NULL,
                'description' => NULL,
                'send_sms_notification' => 0,
                'send_email_notification' => 0,
                'recieve_marketing_email' => 0,
                'calendar_booking' => 1,
                'payment_mode' => NULL,
                'stripe_account_id' => NULL,
                'stripe_customer_account_id' => NULL,
                'mailchimp_subscribe_id' => NULL,
                'canva_subscribe_id' => NULL,
            ),
            4 => 
            array (
                'id' => 9,
                'role_id' => 5,
                'salon_id' => 1,
                'price_tier_id' => 1,
                'panel' => 'Frontend',
                'auth_key' => 'f76de87df3594076225ff21f7d3dcae45d277f34620ca0ed784380187cb7ef06',
                'first_name' => 'Sienna11',
                'last_name' => 'Voigt11',
                'username' => 'maulik12717',
                'email' => 'SiennaVoigt@mailinator.com',
                'email_otp' => NULL,
                'email_verified' => 0,
                'email_verified_at' => NULL,
                'password' => '$2y$10$AVPnNGKy7ZF9FjGI3P6NreyAb7LyNvnqH5YIEHuIUPrRcPMj6Z04.',
                'phone_number' => '312-313-1232',
                'phone_number_otp' => NULL,
                'phone_number_verified' => 0,
                'phone_number_verified_at' => NULL,
                'profile_photo' => NULL,
                'remember_token' => NULL,
                'is_active' => 1,
                'is_active_at' => '2022-03-30 07:32:30',
                'created_at' => '2022-03-30 07:32:30',
                'updated_at' => '2022-04-19 08:59:43',
                'gender' => NULL,
                'date_of_birth' => NULL,
                'address' => NULL,
                'street' => NULL,
                'suburb' => NULL,
                'state' => NULL,
                'postcode' => NULL,
                'description' => NULL,
                'send_sms_notification' => 0,
                'send_email_notification' => 0,
                'recieve_marketing_email' => 0,
                'calendar_booking' => 1,
                'payment_mode' => NULL,
                'stripe_account_id' => NULL,
                'stripe_customer_account_id' => NULL,
                'mailchimp_subscribe_id' => NULL,
                'canva_subscribe_id' => NULL,
            ),
            5 => 
            array (
                'id' => 10,
                'role_id' => 6,
                'salon_id' => 1,
                'price_tier_id' => NULL,
                'panel' => 'Frontend',
                'auth_key' => '7f26b514da6f454f617a1a30cc2c8edee451299412de9a3b17ea364033902dae',
                'first_name' => 'Eve',
                'last_name' => 'Wakefield',
                'username' => 'EveWakefield380',
                'email' => 'EveWakefield@mailinator.com',
                'email_otp' => NULL,
                'email_verified' => 0,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DACmA0X4uI4M3MpI6oazJuYnyN0zROC74GUiJqKmo6Wq1tuRMPTeq',
                'phone_number' => '074-520-7975',
                'phone_number_otp' => NULL,
                'phone_number_verified' => 0,
                'phone_number_verified_at' => NULL,
                'profile_photo' => '1650343391_Screenshot_from_2022-02-02_11-44-55.png',
                'remember_token' => NULL,
                'is_active' => 1,
                'is_active_at' => '2022-03-30 09:43:55',
                'created_at' => '2022-03-30 09:43:55',
                'updated_at' => '2022-04-25 12:04:15',
                'gender' => 'Male',
                'date_of_birth' => '2022-02-27',
                'address' => '70 Lowe Street WARRA QLD 4411',
                'street' => '70 Lowe Street',
                'suburb' => 'WARRA',
                'state' => 'QLD',
                'postcode' => '4411',
                'description' => NULL,
                'send_sms_notification' => 1,
                'send_email_notification' => 0,
                'recieve_marketing_email' => 1,
                'calendar_booking' => 0,
                'payment_mode' => NULL,
                'stripe_account_id' => NULL,
                'stripe_customer_account_id' => 'cus_LZZnYccMk9FHGc',
                'mailchimp_subscribe_id' => NULL,
                'canva_subscribe_id' => NULL,
            ),
            6 => 
            array (
                'id' => 11,
                'role_id' => 6,
                'salon_id' => 1,
                'price_tier_id' => NULL,
                'panel' => 'Frontend',
                'auth_key' => 'fbc6e39162de38a9755ad4d356683dfa6f66eae306f3626899d5e071fb4ab114',
                'first_name' => 'Maulik',
                'last_name' => 'Patel',
                'username' => 'maulik12153',
                'email' => 'maulik12@mailinator.com',
                'email_otp' => NULL,
                'email_verified' => 0,
                'email_verified_at' => NULL,
                'password' => '$2y$10$oJMPD7QXkzMdi8xxolgg7OhvLDIG/XIajVnCyGIm85Qa3myokRYuW',
                'phone_number' => '312-312-3123',
                'phone_number_otp' => NULL,
                'phone_number_verified' => 0,
                'phone_number_verified_at' => NULL,
                'profile_photo' => '1650364809_Screenshot_from_2022-03-21_16-16-26.png',
                'remember_token' => NULL,
                'is_active' => 1,
                'is_active_at' => '2022-04-01 07:58:32',
                'created_at' => '2022-04-01 07:58:32',
                'updated_at' => '2022-04-19 10:40:12',
                'gender' => 'Male',
                'date_of_birth' => '2022-04-05',
                'address' => '1629 Cherry Camp RoadChicago, IL 60626',
                'street' => '1629 Cherry Camp',
                'suburb' => 'RoadChicago',
                'state' => 'IL',
                'postcode' => '60626',
                'description' => '32',
                'send_sms_notification' => 0,
                'send_email_notification' => 0,
                'recieve_marketing_email' => 0,
                'calendar_booking' => 0,
                'payment_mode' => NULL,
                'stripe_account_id' => NULL,
                'stripe_customer_account_id' => 'cus_LVkeIOVfU0fc4O',
                'mailchimp_subscribe_id' => NULL,
                'canva_subscribe_id' => NULL,
            ),
            7 => 
            array (
                'id' => 12,
                'role_id' => 5,
                'salon_id' => 1,
                'price_tier_id' => 1,
                'panel' => 'Frontend',
                'auth_key' => '74ba83b5fc30e89a0c4feb508e74100ef618a6b453f4dcd76b7828f48395b181',
                'first_name' => 'Maureen',
                'last_name' => 'Deforest',
                'username' => 'MaureenADeforest462',
                'email' => 'MaureenADeforest@mailinator.com',
                'email_otp' => NULL,
                'email_verified' => 0,
                'email_verified_at' => NULL,
                'password' => '$2y$10$giPJcPZ/TsOH2KPIFZGxBO5K0mD4Bv4LH2K9uvnUlNpT7w0/Bb0j2',
                'phone_number' => '978-455-2234',
                'phone_number_otp' => NULL,
                'phone_number_verified' => 0,
                'phone_number_verified_at' => NULL,
                'profile_photo' => NULL,
                'remember_token' => NULL,
                'is_active' => 1,
                'is_active_at' => '2022-04-26 10:15:28',
                'created_at' => '2022-04-26 10:15:32',
                'updated_at' => '2022-04-26 10:15:32',
                'gender' => NULL,
                'date_of_birth' => '2022-08-08',
                'address' => NULL,
                'street' => NULL,
                'suburb' => NULL,
                'state' => NULL,
                'postcode' => NULL,
                'description' => NULL,
                'send_sms_notification' => 0,
                'send_email_notification' => 0,
                'recieve_marketing_email' => 0,
                'calendar_booking' => 1,
                'payment_mode' => NULL,
                'stripe_account_id' => NULL,
                'stripe_customer_account_id' => NULL,
                'mailchimp_subscribe_id' => NULL,
                'canva_subscribe_id' => NULL,
            ),
            8 => 
            array (
                'id' => 22,
                'role_id' => 6,
                'salon_id' => 1,
                'price_tier_id' => NULL,
                'panel' => 'Frontend',
                'auth_key' => '3e86a0f6c10beb25cf179342e5b68d01c0351a341255cb05769389620f5751c5',
                'first_name' => 'Maulik',
                'last_name' => 'excel',
                'username' => 'maulikexcel708',
                'email' => 'maulikexcel@mailinator.com',
                'email_otp' => NULL,
                'email_verified' => 1,
                'email_verified_at' => '2022-06-06 07:08:03',
                'password' => '$2y$10$Z/S9/jw.tl3GPkUe5SAfFeUS7T/WivaCCLAQiRZe.NiJtsRup041G',
                'phone_number' => '456-568-4565',
                'phone_number_otp' => NULL,
                'phone_number_verified' => 1,
                'phone_number_verified_at' => '2022-06-06 07:08:03',
                'profile_photo' => NULL,
                'remember_token' => NULL,
                'is_active' => 1,
                'is_active_at' => '2022-06-06 07:08:03',
                'created_at' => '2022-06-06 07:08:03',
                'updated_at' => '2022-06-08 06:25:41',
                'gender' => 'Male',
                'date_of_birth' => '2022-08-08',
                'address' => '2468 Ersel Street
Plano, TX 75024 Ersel',
                'street' => NULL,
                'suburb' => 'Plano',
                'state' => 'TX',
                'postcode' => '75024',
                'description' => 'test',
                'send_sms_notification' => 1,
                'send_email_notification' => 1,
                'recieve_marketing_email' => 0,
                'calendar_booking' => 0,
                'payment_mode' => NULL,
                'stripe_account_id' => NULL,
                'stripe_customer_account_id' => 'cus_LpyHUQ8LszHmWl',
                'mailchimp_subscribe_id' => NULL,
                'canva_subscribe_id' => NULL,
            ),
        ));
        
        
    }
}