<?php

use App\Models\Modules;
use App\Models\Permissions;
use App\Models\RoleAccess;
use Illuminate\Support\Route;
use Illuminate\Support\Str;
/**
 * Henerate UUID.
 *
 * @return uuid
 */
function generateUuid()
{
    return Str::uuid();
}

if (!function_exists('homeRoute')) {
    /**
     * Return the route to the "home" page depending on authentication/authorization is_active.
     *
     * @return string
     */
    function homeRoute()
    {
        if (access()->allow('view-backend')) {
            return 'admin.dashboard';
        } elseif (auth()->check()) {
            return 'frontend.user.dashboard';
        }

        return 'frontend.index';
    }
}

// Global helpers file with misc functions.
if (!function_exists('app_name')) {
    /**
     * Helper to grab the application name.
     *
     * @return mixed
     */
    function app_name()
    {
        return config('app.name');
    }
}

if (!function_exists('access')) {
    /**
     * Access (lol) the Access:: facade as a simple function.
     */
    function access()
    {
        return app('access');
    }
}

if (!function_exists('includeRouteFiles')) {
    /**
     * Loops through a folder and requires all PHP files
     * Searches sub-directories as well.
     *
     * @param $folder
     */
    function includeRouteFiles($folder)
    {
        $directory = $folder;
        $handle = opendir($directory);
        $directory_list = [$directory];

        while (false !== ($filename = readdir($handle))) {
            if ($filename != '.' && $filename != '..' && is_dir($directory . $filename)) {
                array_push($directory_list, $directory . $filename . '/');
            }
        }

        foreach ($directory_list as $directory) {
            foreach (glob($directory . '*.php') as $filename) {
                require $filename;
            }
        }
    }
}

if (!function_exists('getRtlCss')) {
    /**
     * The path being passed is generated by Laravel Mix manifest file
     * The webpack plugin takes the css filenames and appends rtl before the .css extension
     * So we take the original and place that in and send back the path.
     *
     * @param $path
     *
     * @return string
     */
    function getRtlCss($path)
    {
        $path = explode('/', $path);
        $filename = end($path);
        array_pop($path);
        $filename = rtrim($filename, '.css');

        return implode('/', $path) . '/' . $filename . '.rtl.css';
    }
}

if (!function_exists('escapeSlashes')) {
    /**
     * Access the escapeSlashes helper.
     */
    function escapeSlashes($path)
    {
        $path = str_replace('\\', DIRECTORY_SEPARATOR, $path);
        $path = str_replace('//', DIRECTORY_SEPARATOR, $path);
        $path = trim($path, DIRECTORY_SEPARATOR);

        return $path;
    }
}

if (!function_exists('getRouteUrl')) {
    /**
     * Converts querystring params to array and use it as route params and returns URL.
     */
    function getRouteUrl($url, $url_type = 'route', $separator = '?')
    {
        $routeUrl = '';

        if (!empty($url)) {
            if ($url_type == 'route') {
                if (strpos($url, $separator) !== false) {
                    $urlArray = explode($separator, $url);
                    $url = $urlArray[0];
                    parse_str($urlArray[1], $params);
                    $routeUrl = route($url, $params);
                } else {
                    $routeUrl = route($url);
                }
            } else {
                $routeUrl = $url;
            }
        }

        return $routeUrl;
    }
}

if (!function_exists('checkDatabaseConnection')) {
    /**
     * @return bool
     */
    function checkDatabaseConnection()
    {
        try {
            DB::connection()->reconnect();

            return true;
        } catch (Exception $ex) {
            return false;
        }
    }
}

if (!function_exists('encode')) {
    /**
     * @return bool
     */
    function encode($str)
    {
        return base64_encode($str);
    }
}

if (!function_exists('decode')) {
    /**
     * @return bool
     */
    function decode($str)
    {
        return base64_decode($str);
    }
}

if (!function_exists('currentDateTime')) {
    function currentDateTime()
    {
        $format = 'Y-m-d H:i:s';
        return date($format);
    }
}
if (!function_exists('currentDate')) {
    function currentDate()
    {
        $format = 'Y-m-d';
        return date($format);
    }
}
if (!function_exists('currentTime')) {
    function currentTime($format = '24')
    {
        $format = 'H:i:s';
        if ($format == 12) {
            $format = 'H:i A';
        }
        return date($format);
    }
}

if (!function_exists('checkaccess')) {
    function checkaccess($action = "", $controller = "")
    {
        if ($action == 'store') {
            $action = 'create';
        } elseif ($action == 'edit') {
            $action = 'update';
        } elseif ($action == 'accessupdate') {
            $action = 'access';
        }
        $adminuser = auth()->user();
        if ($action && $controller) {
            $modulesdata = Modules::where(['is_active' => '1', 'controller' => $controller, 'action' => $action])->first();
            if (empty($modulesdata)) {
                $modulesdata = Modules::where(['is_active' => '1', 'controller' => $controller])->first();
            }
            if ($modulesdata) {
                $permissionAction = Permissions::where(['module_id' => $modulesdata->id, 'controller' => $controller])->where('action', $action)->first();
                if ($permissionAction) {
                    $module_access = RoleAccess::where(['role_id' => $adminuser->role_id, 'permission_id' => $permissionAction->id, 'access' => '1'])->first();
                    if ($module_access) {
                        return true;
                    }
                } else {
                    $permissionName = Permissions::where(['module_id' => $modulesdata->id, 'controller' => $controller])->where('name', $action)->first();
                    if ($permissionName) {
                        $module_access = RoleAccess::where(['role_id' => $adminuser->role_id, 'permission_id' => $permissionName->id, 'access' => '1'])->first();
                        if ($module_access) {
                            return true;
                        }
                    }
                }
            }
        }
        return false;
    }
}

if (!function_exists('getController')) {
    function getControllerName()
    {
        $action = app('request')->route()->getAction();

        $controller = class_basename($action['controller']);

        list($controller, $action) = explode('@', $controller);
        $current = strtolower(str_replace('Controller', '', $controller));
        return $current;
    }
}

if (!function_exists('getAction')) {
    function getActionName()
    {
        $action = app('request')->route()->getAction();

        $controller = class_basename($action['controller']);

        list($controller, $action) = explode('@', $controller);

        return $action;
    }
}

if (!function_exists('ImageFullUrl')) {
    function ImageFullUrl($image_name, $path)
    {
        return url('storage/' . $path . '/' . $image_name);
    }
}